### ISSUE TITLE
Issue with player tokens 

### ISSUE THREAD

**Issue by Megablokbuster** [doodlezucc/dungeonclub#13]
An issue that I have been having with player tokens is if two players click on the same token then move it in different spots, its offset from the rest of the board. The way ive been able to fix this is for someone to refresh the page

(PS: Love the website, very easy to use with alot of good features)

**Comment by doodlezucc** [comment]
Hi there, sorry for the late response. I remember noticing this issue when playing sessions myself. It can probably be fixed by sending the token's *absolute position* to other players instead of sending only the *movement offset*. Absolute values make synchronization much more straightforward and more stable, naturally. Consider this issue tackled. Also, thanks for visiting the Discord :)

Cheers!

**Comment by doodlezucc** [comment]
This has been (presumably) fixed in the latest https://github.com/doodlezucc/dungeonclub/commit/ab8c3db8f86ea2bed826a774d7711643a490edff commit and will be shipped in the next release update.
