### ISSUE TITLE
QUESTION: how would one go to self-host this project?

### ISSUE THREAD

**Issue by ghost** [doodlezucc/dungeonclub#5]
greetings,

i'm delving into the wonders of self-hosting this amazingly simple tool, but i'm not by any means an expert in web-technologies.

i'm wondering if it is possible to compile everything into one executable for easier time trying to self host it, at least in non-server pcs.

thank you for your time nevertheless and great work !
~ joao

**Comment by doodlezucc** [comment]
Hey, glad you like it!
I think it's certainly possible to self-host Dungeon Club. The whole project is written in Dart, which allows [compiling into native machine code on Windows, macOS and Linux](https://dart.dev/tools/dart-compile#exe).

The tricky part in self-hosting lies in getting two (optional) backend services to work:
1. If you want to use the _integrated audio player_, background music playlists may need to be downloaded (~500 MB). This would require both [youtube-dl](https://youtube-dl.org/) and [ffmpeg](https://ffmpeg.org/download.html) to be installed and on your PATH. (Ambience sound effects will work nonetheless, as they are static files included in this repo.)
2. If you want _users to be able to create an account_, an OAuth 2.0 client is needed to enable mail services. A client can be created and applied to the server with the help of running `<path to server.exe> mail`.

Note that your server would still be able to run and perform normally without these services. If you only plan to self-host to play with your friends, no e-mail registration should be required, naturally! I'll be working out a few things to make it easier to build and run the VTT on your local machine and will update this thread soon. Stay tuned!

Cheers

**Comment by doodlezucc** [comment]
Alright, good news - the first batch of automatically generated builds can be downloaded from the [GitHub Releases tab](https://github.com/doodlezucc/dungeonclub/releases/tag/2022-07-07) right now! Each of the attached `zip`/`tgz` archive files include both a copy of all web/frontend files and a freshly built dedicated server for Windows, MacOS or Linux, ready to launch. :shipit: 

Your operating system is, however, most likely to complain when trying to run the executable `server.exe`. This is due to me not wanting to go broke on code signing certificates which cost a fortune on a monthly basis. Hopefully this won't be much of a problem for self-hosters.

I've also spent some time polishing the _Readme_ to include information about development and self-hosting. If any questions come up, I'd be happy to help!

**Comment by ghost** [comment]
alright, thank you for your hard work!

(hopefuly this comment wont open the issue again)
