### ISSUE TITLE
Additional Movable Commands

### ISSUE THREAD

**Issue by DerinGoulartUlcay** [doodlezucc/dungeonclub#8]
Greetings!

First of all, thank you for developing and sharing this awesome website with the world! 

I briefly attempted to contribute some features on my own but seem to lacking an understanding of how to navigate the dart file ecosystem. Would you be so kind as to either reply with a brief explanation on how to alter movable token commands or help implement the following features?

**User submitted feature request #1:** Movable Token Rotations

Possible implementations:
_(preferred)_ 
When token selected, make Alt+Left Mouse Click  rotate the token character (originally the bottom side) towards the pointer position
_or_ 
When mouse pointer on movable token, make Ctrl or Shift + Left Mouse Drag  rotate the token

**User submitted feature request #2:** User Movement Sequencing Similar to the Measurement Tool

Possible implementation:
When moving a token, make Right Mouse Click leave a point that becomes the new next measurement origin, the cumulative distance is displayed

Thanks again for this beautiful tool!

Best regards,
Derin

**Comment by doodlezucc** [comment]
Hi there, thanks for your feature request!

Right, so *token rotation* is something I hadn't thought of before but which is actually a great addition to the VTT. Kudos for your proposed implementations :)
Regarding the second request, I agree *distance pins* really should be possible when moving tokens across the board to further consistency and overall ease of use.

I'll admit the source code may be a mess to get into right now due to a lack of inline documentation (:trollface:) - sorry about that. I'll have a look at implementing your preferred proposals for the next update and maybe work out some code comments on the way.

Cheers!

**Comment by DerinGoulartUlcay** [comment]
Thank you very much for the quick reply, I appreciate your hard work!

**Comment by doodlezucc** [comment]
Hi, your features have been implemented and can be tested at [dungeonclub.net](https://dungeonclub.net/) right now :) If you've got ideas on how to improve them, let me know.

Cheers!

**Comment by DerinGoulartUlcay** [comment]
Hello!

Thank you for implementing the changes promptly, right on time for the holiday season :) 

The distance pin implementation feels great! As for token rotation, I think it is also a fine addition. I checked it on all the grid types and I like that you have chosen a snapping rotation for the gridded maps and to pointer position for the ungridded map. I have a few questions:

- Is there a reason why you chose the top of the token as the reference/indicator? (Given the token assets provided by 2 minute token editor are downwards facing)
- Do you think it would be difficult to change token rotation on gridded maps so that the rotation can snap to **any** grid cell? (To more distant ones as well) I believe this would make the rotation more intuitive and useful while still preserving the option to snap to the directions you have implemented by choosing the nearest cells.

Thank you and happy holidays!

**Comment by doodlezucc** [comment]
Hi, regarding your questions:
- I picked the top of the token because it seemed the most consistent across code and styling (0° angle = 0° visual rotation), but you're totally right - didn't consider the fact that the assets are actually facing downwards.
- Very neat idea which luckily nowadays should be easy to implement because of the latest grid update and the shared methods of all grid types.

Fortunately, these changes are only frontend related, which means that you can expect to see them on the website later today :)

**Comment by doodlezucc** [comment]
Come to think of it, how do you think tokens that *aren't* snapped to the grid should be rotated?
Should the rotation still snap towards an actual center of a grid cell, or should we fallback to the way rotations are currently done (e.g. simply snapping to any 45° angle on a square grid)?

![Unsnapped token inbetween to grid cells](https://user-images.githubusercontent.com/15276029/209113359-4a99e26d-b36a-40da-a304-3a19cf032b60.png)

**Comment by DerinGoulartUlcay** [comment]
This is a great question! I see value in both your propositions: I think being able to face a grid cell makes more sense while story telling but alligning the token with the grid would indeed be a bit circuitous (first allign position, then rotate, then position back). A few ways you could approach this would be: (with my opinion in parenthesis)

- Implement a way to snap to *both* to grid cells and the angles (most exciting, however this could turn into a disorderly creative coding problem if it's not straight forward to implement)
- Implement a modifier key to snap to angles instead (fullfills most requests but we might be running out of modifier keys)
-  Leave it as is until we collect more feedback/opinions (the circuitous solution it is, which is not that bad)
- Fallback to angle snapping (feels bad for facing other directions/objects)  
- Implement a modifier key to make rotation not snap, a la ungridded map (doesn't actually solve the implicit problem you posed :/ ; but could be a general answer to every future problem )

**Comment by doodlezucc** [comment]
Hey, I've given your first proposed approach a try and it does feel pretty good in my opinion. The changes are visible on the website right now. What are your thoughts?

**Comment by DerinGoulartUlcay** [comment]
Feels great! Thank you!
